### ISSUE TITLE
Update dependency @koa/cors to v5

### ISSUE THREAD

**Issue by flovogt** [lwsjs/cors#5]
Great work! Any plans to update the dependency to latest version of @koa/cors?

**Comment by janpe** [comment]
And this would probably be the reason: https://security.snyk.io/vuln/SNYK-JS-KOACORS-6117545

**Comment by pjammula** [comment]
Hello lwsjs/cors team,
Can you pick this issue and update dependency of @kao/cors to v5?
We are also blackduck violations due to this vulnerability.

**Comment by 75lb** [comment]
Thanks for letting me know and sorry about the delay, I raised an [objection](https://github.com/koajs/cors/issues/94) regarding recent breaking changes in @koa/cors but for now, since it's a trivial issue (returning either `*` or the passed in `origin` have the same effect), I'm working around it. 

Fixed and released in @lwsjs/cors v4.2.1. Please update or reinstall your local-web-server.

**Comment by pjammula** [comment]
Thank you for the quick turn around!
Will re-install and update here.
